server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/movimiento-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      movimientoService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      movimientoService:
        timeoutDuration: 2s